version: "3"
services:
  taurus-constellation-mysql:
    image: mysql:8.0.16
    container_name: taurus-constellation-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=taurus-constellation
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./backend/mysql-db:/docker-entrypoint-initdb.d
      - ./backend/storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined

  backend:
    build: ./backend/
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      - taurus-constellation-mysql
    ports:
      - "3000:80"

  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - taurus-constellation-mysql
    ports:
      - "80:80"

networks:
    default:
        name: constellation-network
